name: Update README with Latest Projects

on:
  schedule:
    - cron: '0 0 * * 0' # chaque dimanche à minuit
  workflow_dispatch: # Permet le lancement manuel

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install axios

      - name: Run update script
        run: node update-readme.js

      - name: Commit and push if README changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "chore: update recent projects in README"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
