name: Update README

on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:

permissions:
  contents: write # <- nécessaire pour push sur le repo

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # pour pousser
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install node-fetch@2
      - run: node update-readme.js
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "update: projets récents" || echo "Pas de changements"
          git push
